// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/message.proto

package core;

/**
 * Protobuf type {@code core.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:core.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    hostName_ = "";
    command_ = 0;
    membershipList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hostName_ = s;
            break;
          }
          case 18: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 34: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              membershipList_ = new java.util.ArrayList<core.Process>();
              mutable_bitField0_ |= 0x00000001;
            }
            membershipList_.add(
                input.readMessage(core.Process.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        membershipList_ = java.util.Collections.unmodifiableList(membershipList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return core.MessageOuterClass.internal_static_core_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return core.MessageOuterClass.internal_static_core_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            core.Message.class, core.Message.Builder.class);
  }

  public static final int HOSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object hostName_;
  /**
   * <code>string hostName = 1;</code>
   * @return The hostName.
   */
  @java.lang.Override
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string hostName = 1;</code>
   * @return The bytes for hostName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  @java.lang.Override
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  public static final int COMMAND_FIELD_NUMBER = 3;
  private int command_;
  /**
   * <code>.core.Command command = 3;</code>
   * @return The enum numeric value on the wire for command.
   */
  @java.lang.Override public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.core.Command command = 3;</code>
   * @return The command.
   */
  @java.lang.Override public core.Command getCommand() {
    @SuppressWarnings("deprecation")
    core.Command result = core.Command.valueOf(command_);
    return result == null ? core.Command.UNRECOGNIZED : result;
  }

  public static final int MEMBERSHIPLIST_FIELD_NUMBER = 4;
  private java.util.List<core.Process> membershipList_;
  /**
   * <code>repeated .core.Process membershipList = 4;</code>
   */
  @java.lang.Override
  public java.util.List<core.Process> getMembershipListList() {
    return membershipList_;
  }
  /**
   * <code>repeated .core.Process membershipList = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends core.ProcessOrBuilder> 
      getMembershipListOrBuilderList() {
    return membershipList_;
  }
  /**
   * <code>repeated .core.Process membershipList = 4;</code>
   */
  @java.lang.Override
  public int getMembershipListCount() {
    return membershipList_.size();
  }
  /**
   * <code>repeated .core.Process membershipList = 4;</code>
   */
  @java.lang.Override
  public core.Process getMembershipList(int index) {
    return membershipList_.get(index);
  }
  /**
   * <code>repeated .core.Process membershipList = 4;</code>
   */
  @java.lang.Override
  public core.ProcessOrBuilder getMembershipListOrBuilder(
      int index) {
    return membershipList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostName_);
    }
    if (timestamp_ != null) {
      output.writeMessage(2, getTimestamp());
    }
    if (command_ != core.Command.JOIN.getNumber()) {
      output.writeEnum(3, command_);
    }
    for (int i = 0; i < membershipList_.size(); i++) {
      output.writeMessage(4, membershipList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostName_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getTimestamp());
    }
    if (command_ != core.Command.JOIN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, command_);
    }
    for (int i = 0; i < membershipList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, membershipList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof core.Message)) {
      return super.equals(obj);
    }
    core.Message other = (core.Message) obj;

    if (!getHostName()
        .equals(other.getHostName())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (command_ != other.command_) return false;
    if (!getMembershipListList()
        .equals(other.getMembershipListList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    if (getMembershipListCount() > 0) {
      hash = (37 * hash) + MEMBERSHIPLIST_FIELD_NUMBER;
      hash = (53 * hash) + getMembershipListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static core.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static core.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static core.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static core.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static core.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static core.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static core.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static core.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static core.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static core.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static core.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static core.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(core.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.Message)
      core.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.MessageOuterClass.internal_static_core_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.MessageOuterClass.internal_static_core_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.Message.class, core.Message.Builder.class);
    }

    // Construct using core.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMembershipListFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hostName_ = "";

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      command_ = 0;

      if (membershipListBuilder_ == null) {
        membershipList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        membershipListBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return core.MessageOuterClass.internal_static_core_Message_descriptor;
    }

    @java.lang.Override
    public core.Message getDefaultInstanceForType() {
      return core.Message.getDefaultInstance();
    }

    @java.lang.Override
    public core.Message build() {
      core.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public core.Message buildPartial() {
      core.Message result = new core.Message(this);
      int from_bitField0_ = bitField0_;
      result.hostName_ = hostName_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      result.command_ = command_;
      if (membershipListBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          membershipList_ = java.util.Collections.unmodifiableList(membershipList_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.membershipList_ = membershipList_;
      } else {
        result.membershipList_ = membershipListBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof core.Message) {
        return mergeFrom((core.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(core.Message other) {
      if (other == core.Message.getDefaultInstance()) return this;
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (membershipListBuilder_ == null) {
        if (!other.membershipList_.isEmpty()) {
          if (membershipList_.isEmpty()) {
            membershipList_ = other.membershipList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembershipListIsMutable();
            membershipList_.addAll(other.membershipList_);
          }
          onChanged();
        }
      } else {
        if (!other.membershipList_.isEmpty()) {
          if (membershipListBuilder_.isEmpty()) {
            membershipListBuilder_.dispose();
            membershipListBuilder_ = null;
            membershipList_ = other.membershipList_;
            bitField0_ = (bitField0_ & ~0x00000001);
            membershipListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembershipListFieldBuilder() : null;
          } else {
            membershipListBuilder_.addAllMessages(other.membershipList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      core.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (core.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object hostName_ = "";
    /**
     * <code>string hostName = 1;</code>
     * @return The hostName.
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @return The bytes for hostName.
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostName() {
      
      hostName_ = getDefaultInstance().getHostName();
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The bytes for hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }

    private int command_ = 0;
    /**
     * <code>.core.Command command = 3;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.core.Command command = 3;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.core.Command command = 3;</code>
     * @return The command.
     */
    @java.lang.Override
    public core.Command getCommand() {
      @SuppressWarnings("deprecation")
      core.Command result = core.Command.valueOf(command_);
      return result == null ? core.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.core.Command command = 3;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(core.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.core.Command command = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<core.Process> membershipList_ =
      java.util.Collections.emptyList();
    private void ensureMembershipListIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        membershipList_ = new java.util.ArrayList<core.Process>(membershipList_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        core.Process, core.Process.Builder, core.ProcessOrBuilder> membershipListBuilder_;

    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public java.util.List<core.Process> getMembershipListList() {
      if (membershipListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(membershipList_);
      } else {
        return membershipListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public int getMembershipListCount() {
      if (membershipListBuilder_ == null) {
        return membershipList_.size();
      } else {
        return membershipListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public core.Process getMembershipList(int index) {
      if (membershipListBuilder_ == null) {
        return membershipList_.get(index);
      } else {
        return membershipListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder setMembershipList(
        int index, core.Process value) {
      if (membershipListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipListIsMutable();
        membershipList_.set(index, value);
        onChanged();
      } else {
        membershipListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder setMembershipList(
        int index, core.Process.Builder builderForValue) {
      if (membershipListBuilder_ == null) {
        ensureMembershipListIsMutable();
        membershipList_.set(index, builderForValue.build());
        onChanged();
      } else {
        membershipListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder addMembershipList(core.Process value) {
      if (membershipListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipListIsMutable();
        membershipList_.add(value);
        onChanged();
      } else {
        membershipListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder addMembershipList(
        int index, core.Process value) {
      if (membershipListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipListIsMutable();
        membershipList_.add(index, value);
        onChanged();
      } else {
        membershipListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder addMembershipList(
        core.Process.Builder builderForValue) {
      if (membershipListBuilder_ == null) {
        ensureMembershipListIsMutable();
        membershipList_.add(builderForValue.build());
        onChanged();
      } else {
        membershipListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder addMembershipList(
        int index, core.Process.Builder builderForValue) {
      if (membershipListBuilder_ == null) {
        ensureMembershipListIsMutable();
        membershipList_.add(index, builderForValue.build());
        onChanged();
      } else {
        membershipListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder addAllMembershipList(
        java.lang.Iterable<? extends core.Process> values) {
      if (membershipListBuilder_ == null) {
        ensureMembershipListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, membershipList_);
        onChanged();
      } else {
        membershipListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder clearMembershipList() {
      if (membershipListBuilder_ == null) {
        membershipList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        membershipListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public Builder removeMembershipList(int index) {
      if (membershipListBuilder_ == null) {
        ensureMembershipListIsMutable();
        membershipList_.remove(index);
        onChanged();
      } else {
        membershipListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public core.Process.Builder getMembershipListBuilder(
        int index) {
      return getMembershipListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public core.ProcessOrBuilder getMembershipListOrBuilder(
        int index) {
      if (membershipListBuilder_ == null) {
        return membershipList_.get(index);  } else {
        return membershipListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public java.util.List<? extends core.ProcessOrBuilder> 
         getMembershipListOrBuilderList() {
      if (membershipListBuilder_ != null) {
        return membershipListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(membershipList_);
      }
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public core.Process.Builder addMembershipListBuilder() {
      return getMembershipListFieldBuilder().addBuilder(
          core.Process.getDefaultInstance());
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public core.Process.Builder addMembershipListBuilder(
        int index) {
      return getMembershipListFieldBuilder().addBuilder(
          index, core.Process.getDefaultInstance());
    }
    /**
     * <code>repeated .core.Process membershipList = 4;</code>
     */
    public java.util.List<core.Process.Builder> 
         getMembershipListBuilderList() {
      return getMembershipListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        core.Process, core.Process.Builder, core.ProcessOrBuilder> 
        getMembershipListFieldBuilder() {
      if (membershipListBuilder_ == null) {
        membershipListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            core.Process, core.Process.Builder, core.ProcessOrBuilder>(
                membershipList_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        membershipList_ = null;
      }
      return membershipListBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:core.Message)
  }

  // @@protoc_insertion_point(class_scope:core.Message)
  private static final core.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new core.Message();
  }

  public static core.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public core.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

