// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package core;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostName = 1;</code>
   * @return The hostName.
   */
  java.lang.String getHostName();
  /**
   * <code>string hostName = 1;</code>
   * @return The bytes for hostName.
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>.core.Command command = 3;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.core.Command command = 3;</code>
   * @return The command.
   */
  core.Command getCommand();
}
