// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/message.proto

package core;

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022core/message.proto\022\004core\032\037google/proto" +
      "buf/timestamp.proto\032\022core/process.proto\"" +
      "\221\001\n\007Message\022\020\n\010hostName\030\001 \001(\t\022-\n\ttimesta" +
      "mp\030\002 \001(\0132\032.google.protobuf.Timestamp\022\036\n\007" +
      "command\030\003 \001(\0162\r.core.Command\022%\n\016membersh" +
      "ipList\030\004 \003(\0132\r.core.Process*=\n\007Command\022\010" +
      "\n\004JOIN\020\000\022\t\n\005LEAVE\020\001\022\010\n\004PING\020\002\022\007\n\003ACK\020\003\022\n" +
      "\n\006UPDATE\020\004B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          core.ProcessOuterClass.getDescriptor(),
        });
    internal_static_core_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_Message_descriptor,
        new java.lang.String[] { "HostName", "Timestamp", "Command", "MembershipList", });
    com.google.protobuf.TimestampProto.getDescriptor();
    core.ProcessOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
