// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/message.proto

package core;

/**
 * Protobuf type {@code core.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:core.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    hostName_ = "";
    timestamp_ = "";
    command_ = 0;
    membership_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hostName_ = s;
            break;
          }
          case 16: {

            port_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            timestamp_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            command_ = rawValue;
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              membership_ = new java.util.ArrayList<core.Process>();
              mutable_bitField0_ |= 0x00000001;
            }
            membership_.add(
                input.readMessage(core.Process.parser(), extensionRegistry));
            break;
          }
          case 50: {
            core.FileOuterClass.File.Builder subBuilder = null;
            if (((bitField0_ & 0x00000001) != 0)) {
              subBuilder = file_.toBuilder();
            }
            file_ = input.readMessage(core.FileOuterClass.File.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(file_);
              file_ = subBuilder.buildPartial();
            }
            bitField0_ |= 0x00000001;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        membership_ = java.util.Collections.unmodifiableList(membership_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return core.MessageOuterClass.internal_static_core_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return core.MessageOuterClass.internal_static_core_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            core.Message.class, core.Message.Builder.class);
  }

  private int bitField0_;
  public static final int HOSTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object hostName_;
  /**
   * <code>string hostName = 1;</code>
   * @return The hostName.
   */
  @java.lang.Override
  public java.lang.String getHostName() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hostName_ = s;
      return s;
    }
  }
  /**
   * <code>string hostName = 1;</code>
   * @return The bytes for hostName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHostNameBytes() {
    java.lang.Object ref = hostName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hostName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PORT_FIELD_NUMBER = 2;
  private long port_;
  /**
   * <code>int64 port = 2;</code>
   * @return The port.
   */
  @java.lang.Override
  public long getPort() {
    return port_;
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private volatile java.lang.Object timestamp_;
  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  @java.lang.Override
  public java.lang.String getTimestamp() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      timestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTimestampBytes() {
    java.lang.Object ref = timestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      timestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 4;
  private int command_;
  /**
   * <code>.core.Command command = 4;</code>
   * @return The enum numeric value on the wire for command.
   */
  @java.lang.Override public int getCommandValue() {
    return command_;
  }
  /**
   * <code>.core.Command command = 4;</code>
   * @return The command.
   */
  @java.lang.Override public core.Command getCommand() {
    @SuppressWarnings("deprecation")
    core.Command result = core.Command.valueOf(command_);
    return result == null ? core.Command.UNRECOGNIZED : result;
  }

  public static final int MEMBERSHIP_FIELD_NUMBER = 5;
  private java.util.List<core.Process> membership_;
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  @java.lang.Override
  public java.util.List<core.Process> getMembershipList() {
    return membership_;
  }
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  @java.lang.Override
  public java.util.List<? extends core.ProcessOrBuilder> 
      getMembershipOrBuilderList() {
    return membership_;
  }
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  @java.lang.Override
  public int getMembershipCount() {
    return membership_.size();
  }
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  @java.lang.Override
  public core.Process getMembership(int index) {
    return membership_.get(index);
  }
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  @java.lang.Override
  public core.ProcessOrBuilder getMembershipOrBuilder(
      int index) {
    return membership_.get(index);
  }

  public static final int FILE_FIELD_NUMBER = 6;
  private core.FileOuterClass.File file_;
  /**
   * <code>optional .core.File file = 6;</code>
   * @return Whether the file field is set.
   */
  @java.lang.Override
  public boolean hasFile() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .core.File file = 6;</code>
   * @return The file.
   */
  @java.lang.Override
  public core.FileOuterClass.File getFile() {
    return file_ == null ? core.FileOuterClass.File.getDefaultInstance() : file_;
  }
  /**
   * <code>optional .core.File file = 6;</code>
   */
  @java.lang.Override
  public core.FileOuterClass.FileOrBuilder getFileOrBuilder() {
    return file_ == null ? core.FileOuterClass.File.getDefaultInstance() : file_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hostName_);
    }
    if (port_ != 0L) {
      output.writeInt64(2, port_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, timestamp_);
    }
    if (command_ != core.Command.JOIN.getNumber()) {
      output.writeEnum(4, command_);
    }
    for (int i = 0; i < membership_.size(); i++) {
      output.writeMessage(5, membership_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getFile());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(hostName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hostName_);
    }
    if (port_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, port_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(timestamp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, timestamp_);
    }
    if (command_ != core.Command.JOIN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, command_);
    }
    for (int i = 0; i < membership_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, membership_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getFile());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof core.Message)) {
      return super.equals(obj);
    }
    core.Message other = (core.Message) obj;

    if (!getHostName()
        .equals(other.getHostName())) return false;
    if (getPort()
        != other.getPort()) return false;
    if (!getTimestamp()
        .equals(other.getTimestamp())) return false;
    if (command_ != other.command_) return false;
    if (!getMembershipList()
        .equals(other.getMembershipList())) return false;
    if (hasFile() != other.hasFile()) return false;
    if (hasFile()) {
      if (!getFile()
          .equals(other.getFile())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HOSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getHostName().hashCode();
    hash = (37 * hash) + PORT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPort());
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTimestamp().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + command_;
    if (getMembershipCount() > 0) {
      hash = (37 * hash) + MEMBERSHIP_FIELD_NUMBER;
      hash = (53 * hash) + getMembershipList().hashCode();
    }
    if (hasFile()) {
      hash = (37 * hash) + FILE_FIELD_NUMBER;
      hash = (53 * hash) + getFile().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static core.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static core.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static core.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static core.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static core.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static core.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static core.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static core.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static core.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static core.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static core.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static core.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(core.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.Message)
      core.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return core.MessageOuterClass.internal_static_core_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return core.MessageOuterClass.internal_static_core_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              core.Message.class, core.Message.Builder.class);
    }

    // Construct using core.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMembershipFieldBuilder();
        getFileFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hostName_ = "";

      port_ = 0L;

      timestamp_ = "";

      command_ = 0;

      if (membershipBuilder_ == null) {
        membership_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        membershipBuilder_.clear();
      }
      if (fileBuilder_ == null) {
        file_ = null;
      } else {
        fileBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return core.MessageOuterClass.internal_static_core_Message_descriptor;
    }

    @java.lang.Override
    public core.Message getDefaultInstanceForType() {
      return core.Message.getDefaultInstance();
    }

    @java.lang.Override
    public core.Message build() {
      core.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public core.Message buildPartial() {
      core.Message result = new core.Message(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.hostName_ = hostName_;
      result.port_ = port_;
      result.timestamp_ = timestamp_;
      result.command_ = command_;
      if (membershipBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          membership_ = java.util.Collections.unmodifiableList(membership_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.membership_ = membership_;
      } else {
        result.membership_ = membershipBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        if (fileBuilder_ == null) {
          result.file_ = file_;
        } else {
          result.file_ = fileBuilder_.build();
        }
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof core.Message) {
        return mergeFrom((core.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(core.Message other) {
      if (other == core.Message.getDefaultInstance()) return this;
      if (!other.getHostName().isEmpty()) {
        hostName_ = other.hostName_;
        onChanged();
      }
      if (other.getPort() != 0L) {
        setPort(other.getPort());
      }
      if (!other.getTimestamp().isEmpty()) {
        timestamp_ = other.timestamp_;
        onChanged();
      }
      if (other.command_ != 0) {
        setCommandValue(other.getCommandValue());
      }
      if (membershipBuilder_ == null) {
        if (!other.membership_.isEmpty()) {
          if (membership_.isEmpty()) {
            membership_ = other.membership_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMembershipIsMutable();
            membership_.addAll(other.membership_);
          }
          onChanged();
        }
      } else {
        if (!other.membership_.isEmpty()) {
          if (membershipBuilder_.isEmpty()) {
            membershipBuilder_.dispose();
            membershipBuilder_ = null;
            membership_ = other.membership_;
            bitField0_ = (bitField0_ & ~0x00000001);
            membershipBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMembershipFieldBuilder() : null;
          } else {
            membershipBuilder_.addAllMessages(other.membership_);
          }
        }
      }
      if (other.hasFile()) {
        mergeFile(other.getFile());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      core.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (core.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object hostName_ = "";
    /**
     * <code>string hostName = 1;</code>
     * @return The hostName.
     */
    public java.lang.String getHostName() {
      java.lang.Object ref = hostName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hostName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @return The bytes for hostName.
     */
    public com.google.protobuf.ByteString
        getHostNameBytes() {
      java.lang.Object ref = hostName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hostName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hostName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHostName() {
      
      hostName_ = getDefaultInstance().getHostName();
      onChanged();
      return this;
    }
    /**
     * <code>string hostName = 1;</code>
     * @param value The bytes for hostName to set.
     * @return This builder for chaining.
     */
    public Builder setHostNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hostName_ = value;
      onChanged();
      return this;
    }

    private long port_ ;
    /**
     * <code>int64 port = 2;</code>
     * @return The port.
     */
    @java.lang.Override
    public long getPort() {
      return port_;
    }
    /**
     * <code>int64 port = 2;</code>
     * @param value The port to set.
     * @return This builder for chaining.
     */
    public Builder setPort(long value) {
      
      port_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 port = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPort() {
      
      port_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object timestamp_ = "";
    /**
     * <code>string timestamp = 3;</code>
     * @return The timestamp.
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        timestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     * @return The bytes for timestamp.
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string timestamp = 3;</code>
     * @param value The timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimestamp() {
      
      timestamp_ = getDefaultInstance().getTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>string timestamp = 3;</code>
     * @param value The bytes for timestamp to set.
     * @return This builder for chaining.
     */
    public Builder setTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      timestamp_ = value;
      onChanged();
      return this;
    }

    private int command_ = 0;
    /**
     * <code>.core.Command command = 4;</code>
     * @return The enum numeric value on the wire for command.
     */
    @java.lang.Override public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.core.Command command = 4;</code>
     * @param value The enum numeric value on the wire for command to set.
     * @return This builder for chaining.
     */
    public Builder setCommandValue(int value) {
      
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.core.Command command = 4;</code>
     * @return The command.
     */
    @java.lang.Override
    public core.Command getCommand() {
      @SuppressWarnings("deprecation")
      core.Command result = core.Command.valueOf(command_);
      return result == null ? core.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.core.Command command = 4;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(core.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.core.Command command = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<core.Process> membership_ =
      java.util.Collections.emptyList();
    private void ensureMembershipIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        membership_ = new java.util.ArrayList<core.Process>(membership_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        core.Process, core.Process.Builder, core.ProcessOrBuilder> membershipBuilder_;

    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public java.util.List<core.Process> getMembershipList() {
      if (membershipBuilder_ == null) {
        return java.util.Collections.unmodifiableList(membership_);
      } else {
        return membershipBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public int getMembershipCount() {
      if (membershipBuilder_ == null) {
        return membership_.size();
      } else {
        return membershipBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public core.Process getMembership(int index) {
      if (membershipBuilder_ == null) {
        return membership_.get(index);
      } else {
        return membershipBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder setMembership(
        int index, core.Process value) {
      if (membershipBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipIsMutable();
        membership_.set(index, value);
        onChanged();
      } else {
        membershipBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder setMembership(
        int index, core.Process.Builder builderForValue) {
      if (membershipBuilder_ == null) {
        ensureMembershipIsMutable();
        membership_.set(index, builderForValue.build());
        onChanged();
      } else {
        membershipBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder addMembership(core.Process value) {
      if (membershipBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipIsMutable();
        membership_.add(value);
        onChanged();
      } else {
        membershipBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder addMembership(
        int index, core.Process value) {
      if (membershipBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMembershipIsMutable();
        membership_.add(index, value);
        onChanged();
      } else {
        membershipBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder addMembership(
        core.Process.Builder builderForValue) {
      if (membershipBuilder_ == null) {
        ensureMembershipIsMutable();
        membership_.add(builderForValue.build());
        onChanged();
      } else {
        membershipBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder addMembership(
        int index, core.Process.Builder builderForValue) {
      if (membershipBuilder_ == null) {
        ensureMembershipIsMutable();
        membership_.add(index, builderForValue.build());
        onChanged();
      } else {
        membershipBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder addAllMembership(
        java.lang.Iterable<? extends core.Process> values) {
      if (membershipBuilder_ == null) {
        ensureMembershipIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, membership_);
        onChanged();
      } else {
        membershipBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder clearMembership() {
      if (membershipBuilder_ == null) {
        membership_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        membershipBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public Builder removeMembership(int index) {
      if (membershipBuilder_ == null) {
        ensureMembershipIsMutable();
        membership_.remove(index);
        onChanged();
      } else {
        membershipBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public core.Process.Builder getMembershipBuilder(
        int index) {
      return getMembershipFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public core.ProcessOrBuilder getMembershipOrBuilder(
        int index) {
      if (membershipBuilder_ == null) {
        return membership_.get(index);  } else {
        return membershipBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public java.util.List<? extends core.ProcessOrBuilder> 
         getMembershipOrBuilderList() {
      if (membershipBuilder_ != null) {
        return membershipBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(membership_);
      }
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public core.Process.Builder addMembershipBuilder() {
      return getMembershipFieldBuilder().addBuilder(
          core.Process.getDefaultInstance());
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public core.Process.Builder addMembershipBuilder(
        int index) {
      return getMembershipFieldBuilder().addBuilder(
          index, core.Process.getDefaultInstance());
    }
    /**
     * <code>repeated .core.Process membership = 5;</code>
     */
    public java.util.List<core.Process.Builder> 
         getMembershipBuilderList() {
      return getMembershipFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        core.Process, core.Process.Builder, core.ProcessOrBuilder> 
        getMembershipFieldBuilder() {
      if (membershipBuilder_ == null) {
        membershipBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            core.Process, core.Process.Builder, core.ProcessOrBuilder>(
                membership_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        membership_ = null;
      }
      return membershipBuilder_;
    }

    private core.FileOuterClass.File file_;
    private com.google.protobuf.SingleFieldBuilderV3<
        core.FileOuterClass.File, core.FileOuterClass.File.Builder, core.FileOuterClass.FileOrBuilder> fileBuilder_;
    /**
     * <code>optional .core.File file = 6;</code>
     * @return Whether the file field is set.
     */
    public boolean hasFile() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .core.File file = 6;</code>
     * @return The file.
     */
    public core.FileOuterClass.File getFile() {
      if (fileBuilder_ == null) {
        return file_ == null ? core.FileOuterClass.File.getDefaultInstance() : file_;
      } else {
        return fileBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    public Builder setFile(core.FileOuterClass.File value) {
      if (fileBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        file_ = value;
        onChanged();
      } else {
        fileBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    public Builder setFile(
        core.FileOuterClass.File.Builder builderForValue) {
      if (fileBuilder_ == null) {
        file_ = builderForValue.build();
        onChanged();
      } else {
        fileBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    public Builder mergeFile(core.FileOuterClass.File value) {
      if (fileBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
            file_ != null &&
            file_ != core.FileOuterClass.File.getDefaultInstance()) {
          file_ =
            core.FileOuterClass.File.newBuilder(file_).mergeFrom(value).buildPartial();
        } else {
          file_ = value;
        }
        onChanged();
      } else {
        fileBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      return this;
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    public Builder clearFile() {
      if (fileBuilder_ == null) {
        file_ = null;
        onChanged();
      } else {
        fileBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    public core.FileOuterClass.File.Builder getFileBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFileFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    public core.FileOuterClass.FileOrBuilder getFileOrBuilder() {
      if (fileBuilder_ != null) {
        return fileBuilder_.getMessageOrBuilder();
      } else {
        return file_ == null ?
            core.FileOuterClass.File.getDefaultInstance() : file_;
      }
    }
    /**
     * <code>optional .core.File file = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        core.FileOuterClass.File, core.FileOuterClass.File.Builder, core.FileOuterClass.FileOrBuilder> 
        getFileFieldBuilder() {
      if (fileBuilder_ == null) {
        fileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            core.FileOuterClass.File, core.FileOuterClass.File.Builder, core.FileOuterClass.FileOrBuilder>(
                getFile(),
                getParentForChildren(),
                isClean());
        file_ = null;
      }
      return fileBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:core.Message)
  }

  // @@protoc_insertion_point(class_scope:core.Message)
  private static final core.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new core.Message();
  }

  public static core.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public core.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

