// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/message.proto

package core;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostName = 1;</code>
   * @return The hostName.
   */
  java.lang.String getHostName();
  /**
   * <code>string hostName = 1;</code>
   * @return The bytes for hostName.
   */
  com.google.protobuf.ByteString
      getHostNameBytes();

  /**
   * <code>int64 port = 2;</code>
   * @return The port.
   */
  long getPort();

  /**
   * <code>string timestamp = 3;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 3;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>.core.Command command = 4;</code>
   * @return The enum numeric value on the wire for command.
   */
  int getCommandValue();
  /**
   * <code>.core.Command command = 4;</code>
   * @return The command.
   */
  core.Command getCommand();

  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  java.util.List<core.Process> 
      getMembershipList();
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  core.Process getMembership(int index);
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  int getMembershipCount();
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  java.util.List<? extends core.ProcessOrBuilder> 
      getMembershipOrBuilderList();
  /**
   * <code>repeated .core.Process membership = 5;</code>
   */
  core.ProcessOrBuilder getMembershipOrBuilder(
      int index);

  /**
   * <code>optional .core.File file = 6;</code>
   * @return Whether the file field is set.
   */
  boolean hasFile();
  /**
   * <code>optional .core.File file = 6;</code>
   * @return The file.
   */
  core.FileOuterClass.File getFile();
  /**
   * <code>optional .core.File file = 6;</code>
   */
  core.FileOuterClass.FileOrBuilder getFileOrBuilder();
}
