// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/process.proto

package core;

public interface ProcessOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.Process)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string timestamp = 1;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 1;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();

  /**
   * <code>int64 port = 3;</code>
   * @return The port.
   */
  long getPort();

  /**
   * <code>.core.ProcessStatus status = 4;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.core.ProcessStatus status = 4;</code>
   * @return The status.
   */
  core.ProcessStatus getStatus();
}
