// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/process.proto

package core;

public final class ProcessOuterClass {
  private ProcessOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_Process_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_Process_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022core/process.proto\022\004core\"`\n\007Process\022\021\n" +
      "\ttimestamp\030\001 \001(\t\022\017\n\007address\030\002 \001(\t\022\014\n\004por" +
      "t\030\003 \001(\003\022#\n\006status\030\004 \001(\0162\023.core.ProcessSt" +
      "atus*@\n\rProcessStatus\022\013\n\007DEFAULT\020\000\022\t\n\005AL" +
      "IVE\020\001\022\n\n\006LEAVED\020\002\022\013\n\007CRASHED\020\003B\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_core_Process_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_Process_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_Process_descriptor,
        new java.lang.String[] { "Timestamp", "Address", "Port", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
