package core;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/message.proto

public final class MessageOuterClass {
  private MessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_core_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\022core/message.proto\022\004core\032\022core/process" +
      ".proto\032\017core/file.proto\"\265\001\n\007Message\022\020\n\010h" +
      "ostName\030\001 \001(\t\022\014\n\004port\030\002 \001(\003\022\021\n\ttimestamp" +
      "\030\003 \001(\t\022\036\n\007command\030\004 \001(\0162\r.core.Command\022!" +
      "\n\nmembership\030\005 \003(\0132\r.core.Process\022\035\n\004fil" +
      "e\030\006 \001(\0132\n.core.FileH\000\210\001\001\022\014\n\004meta\030\007 \001(\tB\007" +
      "\n\005_file*\320\001\n\007Command\022\010\n\004JOIN\020\000\022\t\n\005LEAVE\020\001" +
      "\022\010\n\004PING\020\002\022\007\n\003ACK\020\003\022\n\n\006UPDATE\020\004\022\013\n\007DISPL" +
      "AY\020\005\022\013\n\007WELCOME\020\006\022\022\n\016UPLOAD_REQUEST\020\007\022\n\n" +
      "\006UPLOAD\020\010\022\024\n\020DOWNLOAD_REQUEST\020\t\022\014\n\010DOWNL" +
      "OAD\020\n\022\013\n\007ELECTED\020\013\022\014\n\010READ_ACK\020\014\022\r\n\tWRIT" +
      "E_ACK\020\r\022\t\n\005REPLY\020\016B\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          core.ProcessOuterClass.getDescriptor(),
          core.FileOuterClass.getDescriptor(),
        });
    internal_static_core_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_core_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_core_Message_descriptor,
        new String[] { "HostName", "Port", "Timestamp", "Command", "Membership", "File", "Meta", "File", });
    core.ProcessOuterClass.getDescriptor();
    core.FileOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
